
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        
        labelWinner.setText(Global.gameSummary);
        textfieldWhy.setText(Global.gameSummary2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butonX = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelGameOver = new javax.swing.JLabel();
        labelWinner = new javax.swing.JLabel();
        textfieldWhy = new java.awt.TextArea();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(260, 310));
        setMinimumSize(new java.awt.Dimension(260, 310));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/X.png"))); // NOI18N
        butonX.setBorderPainted(false);
        butonX.setContentAreaFilled(false);
        butonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonXActionPerformed(evt);
            }
        });
        getContentPane().add(butonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 20, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 60));

        labelGameOver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGameOver.setText("Game over!");
        labelGameOver.setToolTipText(null);
        getContentPane().add(labelGameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 10, 240, 60));

        labelWinner.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWinner.setText("jLabel1");
        getContentPane().add(labelWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, -1));

        textfieldWhy.setEditable(false);
        textfieldWhy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textfieldWhy.setRows(30);
        getContentPane().add(textfieldWhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 100));

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TeamSelect-backdrop.png"))); // NOI18N
        labelBackground.setToolTipText(null);
        getContentPane().add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butonXActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //button for quitting current scenario and returning to main menu
        Scenario.killSwitch();

        new MainMenu().setVisible(true);
        GameOver.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelGameOver;
    private javax.swing.JLabel labelWinner;
    private java.awt.TextArea textfieldWhy;
    // End of variables declaration//GEN-END:variables
}
