/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupHelpTypes = new javax.swing.ButtonGroup();
        butonX = new javax.swing.JButton();
        buttonMenu = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHelp = new javax.swing.JTextArea();
        radioBasics = new javax.swing.JRadioButton();
        radioBattles = new javax.swing.JRadioButton();
        radioVictory = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setMaximumSize(new java.awt.Dimension(475, 275));
        setMinimumSize(new java.awt.Dimension(475, 275));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(475, 275));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/X.png"))); // NOI18N
        butonX.setBorderPainted(false);
        butonX.setContentAreaFilled(false);
        butonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonXActionPerformed(evt);
            }
        });
        getContentPane().add(butonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 20, -1));

        buttonMenu.setText("Main Menu");
        buttonMenu.setToolTipText("");
        buttonMenu.setBorder(null);
        buttonMenu.setContentAreaFilled(false);
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 110, 50));

        textHelp.setEditable(false);
        textHelp.setColumns(20);
        textHelp.setLineWrap(true);
        textHelp.setRows(5);
        textHelp.setText("I don't know who you are. I don't know what you want. If you are looking for ransom, I can tell you I don't have money. But what I do have are a very particular set of skills; skills I have acquired over a very long career. Skills that make me a nightmare for people like you. If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you. ");
        textHelp.setToolTipText("");
        textHelp.setWrapStyleWord(true);
        textHelp.setBorder(null);
        textHelp.setMaximumSize(new java.awt.Dimension(160, 90));
        textHelp.setMinimumSize(new java.awt.Dimension(160, 90));
        textHelp.setOpaque(false);
        jScrollPane1.setViewportView(textHelp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 63, 310, 180));

        groupHelpTypes.add(radioBasics);
        radioBasics.setSelected(true);
        radioBasics.setText("The Basics");
        radioBasics.setContentAreaFilled(false);
        radioBasics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBasicsActionPerformed(evt);
            }
        });
        getContentPane().add(radioBasics, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        groupHelpTypes.add(radioBattles);
        radioBattles.setText("Battles");
        radioBattles.setContentAreaFilled(false);
        radioBattles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBattlesActionPerformed(evt);
            }
        });
        getContentPane().add(radioBattles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        groupHelpTypes.add(radioVictory);
        radioVictory.setText("Victory");
        radioVictory.setContentAreaFilled(false);
        radioVictory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVictoryActionPerformed(evt);
            }
        });
        getContentPane().add(radioVictory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HelpScreen-backdrop.png"))); // NOI18N
        jLabel1.setToolTipText(null);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        new MainMenu().setVisible(true);
        HowToPlay.this.dispose();
    }//GEN-LAST:event_buttonMenuActionPerformed

    private void radioBattlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBattlesActionPerformed
        textHelp.setText("Hello. My name is Inigo Montoya. "
                + "You killed my father. Prepare to die. ");
    }//GEN-LAST:event_radioBattlesActionPerformed

    private void radioBasicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBasicsActionPerformed
        textHelp.setText("I don't know who you are. I don't know what "
                + "you want. If you are looking for ransom, I can tell "
                + "you I don't have money. But what I do have are a very "
                + "particular set of skills; skills I have acquired over "
                + "a very long career. Skills that make me a nightmare "
                + "for people like you. If you let my daughter go now, "
                + "that'll be the end of it. I will not look for you, I "
                + "will not pursue you. But if you don't, I will look for "
                + "you, I will find you, and I will kill you. ");
    }//GEN-LAST:event_radioBasicsActionPerformed

    private void radioVictoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVictoryActionPerformed
        textHelp.setText("I don't know half of you half as well as "
                + "I should like; and I like less than half of you "
                + "half as well as you deserve....");
    }//GEN-LAST:event_radioVictoryActionPerformed

    private void butonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butonXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HowToPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonX;
    private javax.swing.JToggleButton buttonMenu;
    private javax.swing.ButtonGroup groupHelpTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBasics;
    private javax.swing.JRadioButton radioBattles;
    private javax.swing.JRadioButton radioVictory;
    private javax.swing.JTextArea textHelp;
    // End of variables declaration//GEN-END:variables
}
