

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class Map extends javax.swing.JFrame {

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        
        if((Global.intOpponent) == 1)
            labelOpponent.setText("Against Player");
        else
            labelOpponent.setText("Against AI");
        
        labelScenario.setText("Scenario: " + Global.intScenario);
        
        panelActions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActions = new javax.swing.JPanel();
        buttonHidePanel = new javax.swing.JButton();
        buttonElement1 = new javax.swing.JButton();
        buttonElement2 = new javax.swing.JButton();
        buttonElement3 = new javax.swing.JButton();
        buttonElement4 = new javax.swing.JButton();
        buttonElement5 = new javax.swing.JButton();
        buttonElement6 = new javax.swing.JButton();
        buttonElement7 = new javax.swing.JButton();
        buttonElement8 = new javax.swing.JButton();
        buttonElement9 = new javax.swing.JButton();
        labelScenario = new javax.swing.JLabel();
        labelOpponent = new javax.swing.JLabel();
        buttonMenu = new javax.swing.JToggleButton();
        buttonExit = new javax.swing.JButton();
        menuInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nodePlaceholder1 = new javax.swing.JButton();
        nodePlaceholder2 = new javax.swing.JButton();
        nodePlaceholder3 = new javax.swing.JButton();
        nodePlaceholder4 = new javax.swing.JButton();
        nodePlaceholder5 = new javax.swing.JButton();
        nodePlaceholder6 = new javax.swing.JButton();
        nodePlaceholder7 = new javax.swing.JButton();
        nodePlaceholder8 = new javax.swing.JButton();
        nodePlaceholder9 = new javax.swing.JButton();
        nodePlaceholder10 = new javax.swing.JButton();
        nodePlaceholder11 = new javax.swing.JButton();
        nodePlaceholder12 = new javax.swing.JButton();
        nodePlaceholder13 = new javax.swing.JButton();
        nodePlaceholder14 = new javax.swing.JButton();
        scenarioMap = new javax.swing.JLabel();
        buttonFinishTurn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActions.setBackground(new java.awt.Color(255, 255, 255));
        panelActions.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelActions.setEnabled(false);

        buttonHidePanel.setText("Hide Menu");
        buttonHidePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHidePanelActionPerformed(evt);
            }
        });

        buttonElement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElement1ActionPerformed(evt);
            }
        });

        buttonElement6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElement6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonElement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonHidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addComponent(buttonElement2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonElement6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addComponent(buttonHidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonElement9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        getContentPane().add(panelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 130, 480));

        labelScenario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelScenario.setText("text");
        getContentPane().add(labelScenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        labelOpponent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelOpponent.setText("text");
        labelOpponent.setName("labelOpponent"); // NOI18N
        getContentPane().add(labelOpponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        buttonMenu.setText("Main Menu");
        buttonMenu.setToolTipText("");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        buttonExit.setText("End Game");
        buttonExit.setMaximumSize(new java.awt.Dimension(83, 23));
        buttonExit.setMinimumSize(new java.awt.Dimension(83, 23));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 90, -1));

        menuInfo.setMaximumSize(new java.awt.Dimension(700, 70));
        menuInfo.setMinimumSize(new java.awt.Dimension(700, 70));

        jLabel1.setText("These");

        jLabel2.setText("Labels");

        jLabel3.setText("Will");

        jLabel4.setText("Readjust");

        jLabel5.setText("are");

        jLabel6.setText("needed");

        jLabel7.setText("as");

        jLabel8.setText("they");

        javax.swing.GroupLayout menuInfoLayout = new javax.swing.GroupLayout(menuInfo);
        menuInfo.setLayout(menuInfoLayout);
        menuInfoLayout.setHorizontalGroup(
            menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuInfoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(146, 146, 146)
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(181, 181, 181)
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(57, 57, 57))
        );
        menuInfoLayout.setVerticalGroup(
            menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(menuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(menuInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        nodePlaceholder1.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder1.setOpaque(false);
        nodePlaceholder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder1ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 30, 30));

        nodePlaceholder2.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder2.setOpaque(false);
        nodePlaceholder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder2ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 30, 30));

        nodePlaceholder3.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder3.setOpaque(false);
        nodePlaceholder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder3ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 30, 30));

        nodePlaceholder4.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder4.setOpaque(false);
        nodePlaceholder4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder4ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 30, 30));

        nodePlaceholder5.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder5.setOpaque(false);
        nodePlaceholder5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder5ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 30, 30));

        nodePlaceholder6.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder6.setOpaque(false);
        nodePlaceholder6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder6ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 30, 30));

        nodePlaceholder7.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder7.setOpaque(false);
        nodePlaceholder7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder7ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 30, 30));

        nodePlaceholder8.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder8.setOpaque(false);
        nodePlaceholder8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder8ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 30, 30));

        nodePlaceholder9.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder9.setOpaque(false);
        nodePlaceholder9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder9ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 30, 30));

        nodePlaceholder10.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder10.setOpaque(false);
        nodePlaceholder10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder10ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 30, 30));

        nodePlaceholder11.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder11.setOpaque(false);
        nodePlaceholder11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder11ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 30, 30));

        nodePlaceholder12.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder12.setOpaque(false);
        nodePlaceholder12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder12ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 30));

        nodePlaceholder13.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder13.setOpaque(false);
        nodePlaceholder13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder13ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 30, 30));

        nodePlaceholder14.setBackground(new java.awt.Color(0, 0, 0));
        nodePlaceholder14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Node-Button.jpg"))); // NOI18N
        nodePlaceholder14.setOpaque(false);
        nodePlaceholder14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodePlaceholder14ActionPerformed(evt);
            }
        });
        getContentPane().add(nodePlaceholder14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 30, 30));

        scenarioMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Map1_Sulla.png"))); // NOI18N
        scenarioMap.setText("jLabel1");
        scenarioMap.setMaximumSize(new java.awt.Dimension(800, 450));
        scenarioMap.setMinimumSize(new java.awt.Dimension(800, 450));
        scenarioMap.setName(""); // NOI18N
        scenarioMap.setPreferredSize(new java.awt.Dimension(800, 450));
        getContentPane().add(scenarioMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 39, -1, -1));

        buttonFinishTurn.setText("Finish Turn");
        getContentPane().add(buttonFinishTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 3, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        new MainMenu().setVisible(true);
        Map.this.dispose();
    }//GEN-LAST:event_buttonMenuActionPerformed
        
    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void nodePlaceholder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder1ActionPerformed
        jLabel9.setText("Derpedy WINNING.");
        panelActions.setVisible(true);
        panelActions.setEnabled(true);
    }//GEN-LAST:event_nodePlaceholder1ActionPerformed

    private void nodePlaceholder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder2ActionPerformed
        
    }//GEN-LAST:event_nodePlaceholder2ActionPerformed

    private void nodePlaceholder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder3ActionPerformed

    private void nodePlaceholder4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder4ActionPerformed

    private void nodePlaceholder5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder5ActionPerformed

    private void nodePlaceholder6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder6ActionPerformed

    private void nodePlaceholder7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder7ActionPerformed

    private void nodePlaceholder8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder8ActionPerformed

    private void nodePlaceholder9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder9ActionPerformed

    private void nodePlaceholder10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder10ActionPerformed

    private void nodePlaceholder11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder11ActionPerformed

    private void nodePlaceholder12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder12ActionPerformed

    private void nodePlaceholder13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder13ActionPerformed

    private void nodePlaceholder14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodePlaceholder14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodePlaceholder14ActionPerformed

    private void buttonElement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElement1ActionPerformed

    }//GEN-LAST:event_buttonElement1ActionPerformed

    private void buttonHidePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHidePanelActionPerformed
        panelActions.setVisible(false);
        panelActions.setEnabled(false);
    }//GEN-LAST:event_buttonHidePanelActionPerformed

    private void buttonElement6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElement6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonElement6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Map().setVisible(true);
            }
            
        });
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonElement1;
    private javax.swing.JButton buttonElement2;
    private javax.swing.JButton buttonElement3;
    private javax.swing.JButton buttonElement4;
    private javax.swing.JButton buttonElement5;
    private javax.swing.JButton buttonElement6;
    private javax.swing.JButton buttonElement7;
    private javax.swing.JButton buttonElement8;
    private javax.swing.JButton buttonElement9;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonFinishTurn;
    private javax.swing.JButton buttonHidePanel;
    private javax.swing.JToggleButton buttonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelOpponent;
    private javax.swing.JLabel labelScenario;
    private javax.swing.JPanel menuInfo;
    private javax.swing.JButton nodePlaceholder1;
    private javax.swing.JButton nodePlaceholder10;
    private javax.swing.JButton nodePlaceholder11;
    private javax.swing.JButton nodePlaceholder12;
    private javax.swing.JButton nodePlaceholder13;
    private javax.swing.JButton nodePlaceholder14;
    private javax.swing.JButton nodePlaceholder2;
    private javax.swing.JButton nodePlaceholder3;
    private javax.swing.JButton nodePlaceholder4;
    private javax.swing.JButton nodePlaceholder5;
    private javax.swing.JButton nodePlaceholder6;
    private javax.swing.JButton nodePlaceholder7;
    private javax.swing.JButton nodePlaceholder8;
    private javax.swing.JButton nodePlaceholder9;
    private javax.swing.JPanel panelActions;
    private javax.swing.JLabel scenarioMap;
    // End of variables declaration//GEN-END:variables
}
