/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prem
 */
public class Teams extends javax.swing.JFrame {

    /**
     * Creates new form Teams
     */
    public Teams() {
        initComponents();
        
        Global.chosenTeam = false;
        
        if(Global.intScenario == 1) {
            radioTeam1.setText("Optimates");
            radioTeam2.setText("Populares");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroupTeam = new javax.swing.ButtonGroup();
        labelTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        labelOr = new javax.swing.JLabel();
        radioTeam1 = new javax.swing.JRadioButton();
        radioTeam2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(265, 330));
        setMinimumSize(new java.awt.Dimension(265, 330));
        setPreferredSize(new java.awt.Dimension(265, 330));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitle.setText("Player 1,");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        labelSubtitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSubtitle.setText("select your team:");
        getContentPane().add(labelSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        labelOr.setText("Or");
        getContentPane().add(labelOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        buttongroupTeam.add(radioTeam1);
        radioTeam1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioTeam1.setSelected(true);
        radioTeam1.setText("jRadioButton1");
        radioTeam1.setContentAreaFilled(false);
        radioTeam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTeam1ActionPerformed(evt);
            }
        });
        getContentPane().add(radioTeam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        buttongroupTeam.add(radioTeam2);
        radioTeam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioTeam2.setText("jRadioButton2");
        radioTeam2.setContentAreaFilled(false);
        radioTeam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTeam2ActionPerformed(evt);
            }
        });
        getContentPane().add(radioTeam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Begin Match");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 240, 250, 60));

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TeamSelect-backdrop.png"))); // NOI18N
        getContentPane().add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Scenario scenario = new Scenario();
        scenario.Initialize(0);
        Global.mapEvent = new MapEvent();
        new Map().setVisible(true);
        Teams.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioTeam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTeam1ActionPerformed
        Global.chosenTeam = false;
    }//GEN-LAST:event_radioTeam1ActionPerformed

    private void radioTeam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTeam2ActionPerformed
        Global.chosenTeam = true;
    }//GEN-LAST:event_radioTeam2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Teams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttongroupTeam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelOr;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JRadioButton radioTeam1;
    private javax.swing.JRadioButton radioTeam2;
    // End of variables declaration//GEN-END:variables
}
